import {UserType} from '../../types/user';

export const Users: UserType[] = [
  {
    id: 1,
    incharge_id: null,
    first_name: 'محمد',
    department_id: 123,
    middle_name: 'علي',
    last_name: 'خان',
    privilege: 'level 2',
    designation: 'موظف',
    username: 'm',
    email: 'mohammed@example.com',
    password: 'p',
    account_status: 'active',
    user_role: 'manager',
  },
  {
    id: 2,
    incharge_id: null,
    first_name: 'فاطمة',
    department_id: 456,
    middle_name: 'محمود',
    last_name: 'علي',
    privilege: 'level 3',
    designation: 'موظف',
    username: 'fatima456',
    email: 'fatima@example.com',
    password: 'password456',
    account_status: 'active',
    user_role: 'investigator',
  },
  {
    id: 3,
    incharge_id: 1,
    first_name: 'علي',
    department_id: 789,
    middle_name: 'مصطفى',
    last_name: 'أحمد',
    privilege: 'level 1',
    designation: 'مدير',
    username: 'ali_mustafa',
    email: 'ali.mustafa@example.com',
    password: 'pass123',
    account_status: 'dormant',
    user_role: 'manager',
  },
  // Add more sample data objects here...
  {
    id: 4,
    incharge_id: 2,
    first_name: 'نورا',
    department_id: 101,
    middle_name: 'عبد الله',
    last_name: 'أحمد',
    privilege: 'level 2',
    designation: 'موظف',
    username: 'nora_ahmed',
    email: 'nora.ahmed@example.com',
    password: 'pass1234',
    account_status: 'active',
    user_role: 'investigator',
  },
  {
    id: 5,
    incharge_id: 3,
    first_name: 'رامي',
    department_id: 202,
    middle_name: 'محمود',
    last_name: 'سعيد',
    privilege: 'level 1',
    designation: 'مدير',
    username: 'ramy_saeed',
    email: 'ramy.saeed@example.com',
    password: 'pass12345',
    account_status: 'active',
    user_role: 'manager',
  },
  // Add more sample data objects here...
];
